export const dish= [
        {
          id: 1,
          name: "Burger",
          Description: "Description about food",
          price: 250,
          inCart: false,
          count: 0,
          total: 0,
        },
        {  
          id: 2,
          name: "Burger",
          Description: "Description about food",
          price: 250,
          inCart: false,
          count: 0,
          total: 0,
        },
        {
           id: 3,
          name: "Burger",
          Description: "Description about food",
          price: 250,
          inCart: false,
          count: 0,
          total: 0,
        },
        {
          id: 4,
          name: "Burger",
          Description: "Description about food",
          price: 250,
          inCart: false,
          count: 0,
          total: 0,
        },
        { 
           id: 5,
          name: "Burger",
          Description: "Description about food",
          price: 250,
          inCart: false,
          count: 0,
          total: 0,
        },
        {
           id: 6,
          name: "Burger",
          Description: "Description about food",
          price: 250,
          inCart: false,
          count: 0,
          total: 0,
        },
        {
           id: 7,
          name: "Burger",
          Description: "Description about food",
          price: 250,
          inCart: false,
          count: 0,
          total: 0,
        },
        {
           id: 8,
          name: "Burger",
          Description: "Description about food",
          price: 250,
          inCart: false,
          count: 0,
          total: 0,
        },
        {
           id: 9,
          name: "Burger",
          Description: "Description about food",
          price: 250,
          inCart: false,
          count: 0,
          total: 0,
        },
        {
           id: 10,
          name: "Burger",
          Description: "Description about food",
          price: 250,
          inCart: false,
          count: 0,
          total: 0,
        },
      ]